#!/bin/bash
#Script Add Trojan

red='\e[38;1;31m'
green='\e[38;1;32m'
yellow='\e[38;1;33m'
blue='\e[38;5;27m'
purple='\e[38;5;166m'
WhiteB="\e[5;37m"
BlueCyan="\e[38;1;36m"
Green_background="\033[42;37m"
Red_background="\033[41;37m"
bgPutih="\e[1;47;30m"
white='\e[0;37m'
plain='\e[0m'
Suffix="\033[0m"
NC='\e[0m'
keatas="${BlueCyan}│${plain}"
ON="${green}ON${plain}"
OFF="${red}OFF${plain}"
jari="${yellow}☞${plain}"

function laneTop() {
  echo -e "${BlueCyan}┌─────────────────────────────────────────────────┐${plain}"
}
function laneBot() {
  echo -e "${BlueCyan}└─────────────────────────────────────────────────┘${plain}"
}
function laneTop1() {
  echo -e "   ${BlueCyan}┌───────────────────────────────────────────┐${plain}"
}
function laneBot1() {
  echo -e "   ${BlueCyan}└───────────────────────────────────────────┘${plain}"
}
function laneTop2() {
  echo -e "     ${BlueCyan}┌───────────────────────────────────────┐${plain}"
}
function laneBot2() {
  echo -e "     ${BlueCyan}└───────────────────────────────────────┘${plain}"
}
function LOGO() {
	clear
	laneTop
	echo -e "${keatas} ${bgPutih}              AUTOSKRIP KAIZENVPS              ${plain} ${keatas}"
	laneBot
	echo -e ""
}

function Credit_KaizenVPS() {
	clear
	echo -e ""
	laneTop
	echo -e "${keatas} ${bgPutih} TERIMA KASIH KERANA MENGGUNAKAN AUTOSKRIP INI ${plain} ${keatas}"
	laneBot
	echo -e ""
	exit 0
}


laneTop
	echo -e "${keatas} ${bgPutih}             MEMBUAT AKAUN TROJAN              ${plain} ${keatas}"
	laneBot
	echo ""
	echo -e " Sila taip dalam format nombor:-"
	echo -e ""
	echo -e " ${Green}Limit Kuota (Dalam format GB)${Suffix}"
	echo -e " Sila taip ${yellow}0${Suffix} untuk Unlimited Kuota"
	echo -e ""
	echo -e " ${Green}Limit IP Address${Suffix}"
	echo -e " Sila taip ${yellow}0${Suffix} untuk Tiada Limit IP Address"
	echo -e " Atau taip ${yellow}1${Suffix} sekiranya anda mahu mencegah Multilogin"
	echo -e ""
	echo -e "${BlueCyan}───────────────────────────────────────────────────${Suffix}"
	echo -e ""

echo -e ""
LOGO
echo -e "     1.)  Semua Jenis Akaun Trojan"
echo -e "     2.)  Trojan WS"
echo -e "     3.)  Trojan GRPC"
echo -e "     4.)  Kembali ke Menu Utama"
echo -e "     x.)  Exit"
echo -e ""
echo -e "${BlueCyan}───────────────────────────────────────────────────${plain}"
echo -e ""

echo -e ""
LOGO
echo -e "     ${green}[ 1 ]${plain} ► Semua Jenis Akaun Trojan"
echo -e "     ${green}[ 2 ]${plain} ► Trojan WS"
echo -e "     ${green}[ 3 ]${plain} ► Trojan GRPC"
echo -e "     ${green}[ 4 ]${plain} ► Kembali ke Menu Utama"
echo -e "     ${green}[ x ]${plain} ► Exit"
echo -e ""
echo -e "${BlueCyan}───────────────────────────────────────────────────${plain}"
echo -e ""
