#!/bin/bash
#Script Add Trojan

red='\e[38;1;31m'
green='\e[38;1;32m'
yellow='\e[38;1;33m'
blue='\e[38;5;27m'
purple='\e[38;5;166m'
WhiteB="\e[5;37m"
BlueCyan="\e[38;1;36m"
Green_background="\033[42;37m"
Red_background="\033[41;37m"
bgPutih="\e[1;47;30m"
white='\e[0;37m'
plain='\e[0m'
Suffix="\033[0m"
NC='\e[0m'
keatas="${BlueCyan}│${plain}"
ON="${green}ON${plain}"
OFF="${red}OFF${plain}"
jari="${yellow}☞${plain}"

function laneTop() {
  echo -e "${BlueCyan}┌─────────────────────────────────────────────────┐${plain}"
}
function laneBot() {
  echo -e "${BlueCyan}└─────────────────────────────────────────────────┘${plain}"
}
function laneTop1() {
  echo -e "   ${BlueCyan}┌───────────────────────────────────────────┐${plain}"
}
function laneBot1() {
  echo -e "   ${BlueCyan}└───────────────────────────────────────────┘${plain}"
}
function laneTop2() {
  echo -e "     ${BlueCyan}┌───────────────────────────────────────┐${plain}"
}
function laneBot2() {
  echo -e "     ${BlueCyan}└───────────────────────────────────────┘${plain}"
}
function LOGO() {
	laneTop
	echo -e "${keatas} ${bgPutih}              AUTOSKRIP KAIZENVPS              ${plain} ${keatas}"
	laneBot
	echo -e ""
}

function Credit_KaizenVPS() {
	clear
	echo -e ""
	laneTop
	echo -e "${keatas} ${bgPutih} TERIMA KASIH KERANA MENGGUNAKAN AUTOSKRIP INI ${plain} ${keatas}"
	laneBot
	echo -e ""
	exit 0
}


	echo -e "${keatas} ${bgPutih}             MEMBUAT AKAUN TRIAL               ${plain} ${keatas}"
	laneBot
	echo -e ""
	echo -e "  Format Masa :"
	echo -e ""
	echo -e "  ${green}h - H (Hours)${Suffix}"
	echo -e "  ${green}m - M (Minutes)${Suffix}"
	echo -e ""
	echo -e "  Contoh1 : ${yellow}1h${Suffix} untuk ${yellow}1 jam${Suffix}"
	echo -e "  Contoh2 : ${yellow}10m${Suffix} untuk ${yellow}10 minit${Suffix}"
	echo -e ""
