#!/bin/bash

BLUE='\e[1;36m'
PURPLE='\e[1;35m'
GREEN='\e[1;32m'
RED='\e[1;31m'
YELLOW='\e[1;33m'
WHITE='\e[1m'
NOCOLOR='\e[0m'
TODAY=$(date +"%s")

function revokeIptv() {
	while IFS= read -r LINE; do
		EXP_DATE=$(echo $LINE | sed -ne 's|.*EXP_DATE=\(.*\) URL.*$|\1|p')
		UUID=$(echo $LINE | sed -ne "s|^UUID=\(.*\) USERNAME.*${EXP_DATE}.*$|\1|p")
		USERNAME=$(echo $LINE | sed -ne "s|.*${UUID} USERNAME=\(.*\) EXP_DATE.*$|\1|p")
		EXP_DATE_IN_SECOND=$(date -d "${EXP_DATE}" +"%s")
		EXPIRED=$(( EXP_DATE_IN_SECOND - TODAY ))
		if [[ $EXPIRED -le 0 ]]; then
			cp -f /etc/fqdmnsystem/iptv/exp.html /var/www/html/iptv/${UUID}.html
			echo -e ${USERNAME}
		fi
	done < /etc/fqdmnsystem/iptv/userlist.txt
}
rm -rf /var/log/letsencrypt/letsencrypt.log*
revokeIptv
